Repository DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch, pull requests merged in 2023-09, with the labels that each got.

#111 [Refactor] File Optimization
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/TheoNaView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
Labels: Refactor

#112 [Feat] Localization Support
  ChuckchuDrivenDevelopment/CDDWatchApp Watch App/ContentView.swift
  ChuckchuDrivenDevelopment/CDDWatchApp Watch App/TextModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/onBoarding.imageset/onBoarding_2.jpg
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/DataModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/TextModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/DailyNotiToggleRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/IfDailyNotiOffCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/FrequencySettingRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/TimePickerRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/SettingInfomationCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView1.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView2.swift
  ChuckchuDrivenDevelopment/en.lproj/InfoPlist.strings
  ChuckchuDrivenDevelopment/en.lproj/Localizable.strings
  ChuckchuDrivenDevelopment/ko.lproj/InfoPlist.strings
  ChuckchuDrivenDevelopment/ko.lproj/Localizable.strings
Labels: Feat

#114 [Feat] Device Landscape Prevention
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
Labels: Feat

#124 [Feat] 시작/종료 알림 멘트를 추가했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/AppDelegate.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
  ChuckchuDrivenDevelopment/en.lproj/Localizable.strings
  ChuckchuDrivenDevelopment/ko.lproj/Localizable.strings
Labels: Feat, 리앤
