Repository DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch, pull requests merged in 2023-08, with the labels that each got.

#68 [Refactor] MainView Minor Bug Fix
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
Labels: 띠오, Refactor

#72 [Feat] Tilting Experience Improvement
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift
Labels: Feat, 띠오

#76 [Feat] Tilting Experience Improvement
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift
Labels: Feat, 띠오

#81 [Feat] 하루만 알림끄기 로직을 연결합니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Info.plist
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Feat, 알렉스

#87 Connect OnBoardingView
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView1.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView2.swift
Labels: 띠오, Chore

#90 [Style] Weekday Modify
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/ModalView/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/ModalView/SelectNotificationDay.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/NotificationSettingsCell.swift
Labels: Style, 띠오

#92 [Style] POSTECH notation correction
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift
Labels: Style, 띠오

#94 [Refactor] Oh My God
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/CharacterAnimation/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/DataModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/FloatHeart.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/FontView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/ParallaxMotionModifier.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/TouchDownGestureModifier.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/WheelPickerView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/DailyNotiToggleRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/DayOffToggleView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/ModalView/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/IfDailyNotiOffCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/FrequencySettingRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/SelectedDayRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/TimePickerRow.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/SettingInfomationCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView1.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Onboardings/OnBoardingView2.swift
Labels: 띠오, Refactor

#96 [Refactor] 출시 전 마지막 점검 및 버그 수정을 진행했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/TimePickerRow.swift
Labels: 리앤, Refactor

#98 [HotFix] 오류가 뜨는 오프닝, 클로징 알림 멘트를 임시적으로 제거했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/xcshareddata/xcschemes/CDDWatchApp Watch App.xcscheme
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
Labels: HotFix

#100 [HotFix] DayOffToggleButton Algorithm Fix
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
Labels: HotFix

#103 [HotFix] Correcting Incorrect Information
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/SettingInfomationCell.swift
Labels: HotFix

#106 #101/Feat-AttemptWatchOS-TheoPark
  ChuckchuDrivenDevelopment/CDDWatchApp Watch App/ContentView.swift
  ChuckchuDrivenDevelopment/CDDWatchApp Watch App/WCSettingWatch.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/DataModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/WCSettingMoblie.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/ModalView.swift
Labels: Feat

#108 [Fix] 주말 요일 값 제외 로직 추가
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Components/DataModels.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/MainView/SettingCell/ModalView/ModalView.swift
Labels: HotFix
