Repository DeveloperAcademy-POSTECH/MC3-Team10-CenterWatch, pull requests merged in 2023-07, with the labels that each got.

#5 #3/feat Firebase 통신을 위한 모델과 뷰모델을 구현했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/Group.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/Member.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/Poke.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/SampleModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/SampleViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/GroupViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/MemberViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/PokeViewModel.swift
Labels: Feat, 리앤

#11 #9/feat add notification setting modal view theo park
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/MemberGroup.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/GroupViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Feat

#13 [Refactor] 알림 설정 뷰 내부 구조 리팩토링
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Refactor

#22 [Feat] MainView UI 구현
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Feat, 띠오

#20 [Feat] 스플래시 뷰 구현
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SplashView.swift
Labels: Feat, 띠오

#24 [Style] MainView의 스타일을 개선했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
Labels: Style, 띠오

#25 [Style] MainView 스타일 마이너 개선
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
Labels: Style, 띠오

#28 #16/feat 찌르기와 로컬 푸시 알림을 구현했습니다.
  .gitattributes.txt
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/AppDelegate.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/AccentColor.colorset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/turtle.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/turtle.imageset/turtle.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ContentView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Info.plist
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/Member.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/MemberGroup.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Models/Poke.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationTestingView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationIntervalEnum.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationTitle.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/PokeNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/PushNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/MemberGroupViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/MemberViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/PokeViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Alex/PokeUserTestHomeView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Alex/PokeUserTestListView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Alex/PokeUserTestNameView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/CustomHourPicker.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Feat, 리앤

#32 [Feat] 캐릭터 이스터에그를 추가하였습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d1.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d1.imageset/pin_0001.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d2.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d2.imageset/pin_0002.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d3.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d3.imageset/pin_0003.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d4.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin2d4.imageset/pin_0004.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d1.imageset/0001.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d1.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d2.imageset/0002.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d2.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d3.imageset/0003.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d3.imageset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d4.imageset/0004.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterFrames.xcassets/pin3d4.imageset/Contents.json
Labels: Feat, 테오

#36 [Style] Pretendard 폰트 추가
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Info.plist
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Resources/Pretendard-Bold.otf
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Resources/Pretendard-Medium.otf
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Style, 띠오

#39 [Feat] SpalshView Animation Timing Improvement
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SplashView.swift
Labels: Feat, 띠오

#45 [Feat] 햅틱 피드백 추가
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/SelectNotificationDay.swift
Labels: Feat, 띠오

#47 [Feat] AddTilting in MainView
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift
Labels: Feat, 띠오

#48 [Feat] Haptic Feedback Algorithm Improvement
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
Labels: Feat, 띠오

#52 [Refactor] LocalPushNotificationManger 로직을 리팩토링 하고 추가 작업을 진행했습니다.
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/AppDelegate.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopmentApp.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ContentView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Info.plist
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/LocalNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/MiniTestingView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/NotificationIntervalEnum.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/PokeNotificationManager.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/PushNotification/WeekdayCalculator.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/MemberGroupViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/MemberViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/ViewModels/PokeViewModel.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Alex/PokeUserTestListView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/Alex/PokeUserTestNameView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/CustomHourPicker.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingModalView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
Labels: Feat, 리앤, Refactor

#57 [Style] MainView Style Improvement
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/NotificationSettingsCell.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/ParallaxMotionModifier.swift
Labels: Style, 띠오

#59 [Feat] AddHeartFloatingAction
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment.xcodeproj/project.pbxproj
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Assets.xcassets/AppIcon.appiconset/Contents.json
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoNa/CharacterAnimation.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/FloatHeart.swift
  ChuckchuDrivenDevelopment/ChuckchuDrivenDevelopment/Views/TheoPark/MainView.swift
Labels: Feat, 띠오
